const $ = s => document.querySelector(s);
let sb = null;
let state = { muc_giam:[], bo_luat:[] };
let current = null;
const n = (v,d=null)=>(v===""||v==null?d:Number(v));
const todayISO=()=>new Date().toISOString().slice(0,10);
const setStatus=t=>$("#status").textContent=t;
function emptyLaw(){return {id:null,ma_bo_luat:"",ten_bo_luat:"",mo_ta:"",version:1,hieu_luc_tu:todayISO(),hieu_luc_den:"",do_uu_tien:100,dang_ap_dung:false,pham_vi:[],size_kho:[],dieu_kien:[]};}

async function loadAll(){
  setStatus("Đang tải cấu hình...");
  const {data,error}=await sb.rpc("rpc_xa_admin_get_v1"); if(error) throw error;
  state=data||{muc_giam:[],bo_luat:[]}; renderList();
  if(!current&&state.bo_luat.length) selectLaw(state.bo_luat[0].id); else if(!state.bo_luat.length){current=emptyLaw();renderEditor();}
  setStatus(`Đã tải ${state.bo_luat.length} bộ luật.`);
}
function renderList(){const box=$("#lawList");box.innerHTML="";state.bo_luat.forEach(x=>{const d=document.createElement("div");d.className="law"+(current?.id===x.id?" active":"");d.innerHTML=`<b>${x.ten_bo_luat}</b><small>${x.ma_bo_luat} · v${x.version} · ${x.dang_ap_dung?"Đang áp dụng":"Tạm tắt"}</small>`;d.onclick=()=>selectLaw(x.id);box.appendChild(d);});}
function selectLaw(id){const src=state.bo_luat.find(x=>x.id===id);current=JSON.parse(JSON.stringify(src));renderList();renderEditor();}
function renderEditor(){const x=current||emptyLaw();["ma_bo_luat","ten_bo_luat","version","do_uu_tien","hieu_luc_tu","hieu_luc_den","mo_ta"].forEach(k=>$("#"+k).value=x[k]??"");$("#dang_ap_dung").value=String(!!x.dang_ap_dung);renderScopes();renderSizes();renderRules();}
function pullHeader(){Object.assign(current,{ma_bo_luat:$("#ma_bo_luat").value.trim().toUpperCase(),ten_bo_luat:$("#ten_bo_luat").value.trim(),version:n($("#version").value,1),do_uu_tien:n($("#do_uu_tien").value,100),hieu_luc_tu:$("#hieu_luc_tu").value||todayISO(),hieu_luc_den:$("#hieu_luc_den").value||null,mo_ta:$("#mo_ta").value.trim()||null,dang_ap_dung:$("#dang_ap_dung").value==="true"});}
function delRow(arr,i,render){arr.splice(i,1);render();}

function bindRow(tr,r){tr.querySelectorAll("[data-k]").forEach(el=>el.onchange=()=>{const k=el.dataset.k;if(k==="yeu_cau_tat_ca_size_kho")r[k]=el.value===""?null:(el.value==="true");else if(el.type==="checkbox")r[k]=el.checked;else if(el.type==="number")r[k]=n(el.value);else if(k==="muc_giam_pct")r[k]=Number(el.value);else r[k]=el.value;});}
function renderScopes(){const tb=$("#scopeBody");tb.innerHTML="";(current.pham_vi||[]).forEach((r,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><select data-k="loai_pham_vi"><option>NHOMHANG</option><option>CHUNGLOAI</option><option>NHACC</option><option>MASP</option></select></td><td><input data-k="gia_tri" value="${r.gia_tri??""}"></td><td><input data-k="do_uu_tien" type="number" value="${r.do_uu_tien??100}"></td><td><input data-k="dang_ap_dung" type="checkbox" ${r.dang_ap_dung!==false?"checked":""}></td><td><button class="btn secondary">X</button></td>`;tr.querySelector('[data-k="loai_pham_vi"]').value=r.loai_pham_vi||"NHOMHANG";bindRow(tr,r);tr.querySelector("button").onclick=()=>delRow(current.pham_vi,i,renderScopes);tb.appendChild(tr);});}
function renderSizes(){const tb=$("#sizeBody");tb.innerHTML="";(current.size_kho||[]).forEach((r,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><select data-k="kieu_dieu_kien"><option>BANG</option><option>TU_SO</option><option>DEN_SO</option><option>KHOANG_SO</option></select></td><td><input data-k="size_cu_the" value="${r.size_cu_the??""}"></td><td><input data-k="size_tu" type="number" step="0.01" value="${r.size_tu??""}"></td><td><input data-k="size_den" type="number" step="0.01" value="${r.size_den??""}"></td><td><input data-k="do_uu_tien" type="number" value="${r.do_uu_tien??100}"></td><td><input data-k="dang_ap_dung" type="checkbox" ${r.dang_ap_dung!==false?"checked":""}></td><td><button class="btn secondary">X</button></td>`;tr.querySelector('[data-k="kieu_dieu_kien"]').value=r.kieu_dieu_kien||"BANG";bindRow(tr,r);tr.querySelector("button").onclick=()=>delRow(current.size_kho,i,renderSizes);tb.appendChild(tr);});}
function discountOptions(){return `<select data-k="muc_giam_pct">${state.muc_giam.filter(x=>x.dang_ap_dung!==false).map(x=>`<option value="${x.pct}">${x.pct}%</option>`).join("")}</select>`;}
function renderRules(){const tb=$("#ruleBody");tb.innerHTML="";(current.dieu_kien||[]).forEach((r,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td style="min-width:190px"><input data-k="ma_rule" value="${r.ma_rule??""}" placeholder="MA_RULE"><input data-k="ten_rule" value="${r.ten_rule??""}" placeholder="Tên rule" style="margin-top:4px"></td><td><input data-k="do_uu_tien" type="number" value="${r.do_uu_tien??100}"></td><td><input data-k="tuoi_hang_thang_tu" type="number" step="0.1" value="${r.tuoi_hang_thang_tu??""}" placeholder="Từ"><input data-k="tuoi_hang_thang_den" type="number" step="0.1" value="${r.tuoi_hang_thang_den??""}" placeholder="Đến" style="margin-top:4px"></td><td><input data-k="so_thang_khong_nhap_tu" type="number" step="0.1" value="${r.so_thang_khong_nhap_tu??""}" placeholder="Tháng"><input data-k="so_ngay_khong_nhap_tu" type="number" value="${r.so_ngay_khong_nhap_tu??""}" placeholder="Hoặc ngày" style="margin-top:4px"></td><td><input data-k="so_ngay_khong_ban_tu" type="number" value="${r.so_ngay_khong_ban_tu??""}"></td><td><input data-k="ton_tu" type="number" value="${r.ton_tu??""}" placeholder="Từ"><input data-k="ton_den" type="number" value="${r.ton_den??""}" placeholder="Đến" style="margin-top:4px"></td><td><input data-k="tyle_ton_toi_da" type="number" step="0.01" value="${r.tyle_ton_toi_da??""}" placeholder="0.20"></td><td><select data-k="yeu_cau_tat_ca_size_kho"><option value="">Không xét</option><option value="true">Tất cả size khó</option><option value="false">Không phải tất cả</option></select></td><td>${discountOptions()}</td><td><input data-k="dang_ap_dung" type="checkbox" ${r.dang_ap_dung!==false?"checked":""}></td><td><button class="btn secondary">X</button></td>`;tr.querySelector('[data-k="yeu_cau_tat_ca_size_kho"]').value=r.yeu_cau_tat_ca_size_kho==null?"":String(r.yeu_cau_tat_ca_size_kho);tr.querySelector('[data-k="muc_giam_pct"]').value=String(r.muc_giam_pct||20);bindRow(tr,r);tr.querySelector("button").onclick=()=>delRow(current.dieu_kien,i,renderRules);tb.appendChild(tr);});}
function validateCurrent(){pullHeader();if(!current.ma_bo_luat||!current.ten_bo_luat)throw new Error("Mã và tên bộ luật là bắt buộc.");for(const r of current.dieu_kien||[]){if(!r.ma_rule||!r.ten_rule)throw new Error("Mỗi rule phải có mã và tên.");if(r.so_thang_khong_nhap_tu!=null&&r.so_ngay_khong_nhap_tu!=null)throw new Error(`Rule ${r.ma_rule}: chỉ nhập tháng HOẶC ngày không nhập.`);if(!r.muc_giam_pct)throw new Error(`Rule ${r.ma_rule}: chưa chọn mức giảm.`);}}
async function save(){try{validateCurrent();setStatus("Đang lưu...");const payload={bo_luat:current,pham_vi:current.pham_vi||[],size_kho:current.size_kho||[],dieu_kien:current.dieu_kien||[]};const {data,error}=await sb.rpc("rpc_xa_admin_save_bo_luat_v1",{p_payload:payload});if(error)throw error;current.id=data.id;await loadAll();selectLaw(data.id);setStatus("Đã lưu.");}catch(e){alert("Không lưu được: "+(e.message||e));setStatus("Lỗi lưu.");}}
function newLaw(){current=emptyLaw();renderList();renderEditor();}
function cloneLaw(){if(!current)return;current=JSON.parse(JSON.stringify(current));current.id=null;current.ma_bo_luat=(current.ma_bo_luat||"BO_LUAT")+"_COPY";current.ten_bo_luat=(current.ten_bo_luat||"Bộ luật")+" - Bản sao";current.version=Number(current.version||1)+1;current.dang_ap_dung=false;current.hieu_luc_tu=todayISO();current.hieu_luc_den=null;(current.pham_vi||[]).forEach(x=>delete x.id);(current.size_kho||[]).forEach(x=>delete x.id);(current.dieu_kien||[]).forEach(x=>delete x.id);renderList();renderEditor();}
async function del(){if(!current?.id){newLaw();return;}if(!confirm(`Xóa bộ luật ${current.ma_bo_luat}?`))return;const {error}=await sb.rpc("rpc_xa_admin_delete_bo_luat_v1",{p_id:current.id});if(error){alert(error.message);return;}current=null;await loadAll();}
export async function initQuanLyLuatXa(){sb=window.supabase;if(!sb){alert("Supabase chưa sẵn sàng.");return;}$("#btnNew").onclick=newLaw;$("#btnClone").onclick=cloneLaw;$("#btnSave").onclick=save;$("#btnSave2").onclick=save;$("#btnDelete").onclick=del;$("#btnAddScope").onclick=()=>{current.pham_vi.push({loai_pham_vi:"NHOMHANG",gia_tri:"",do_uu_tien:100,dang_ap_dung:true});renderScopes();};$("#btnAddSize").onclick=()=>{current.size_kho.push({kieu_dieu_kien:"BANG",size_cu_the:"",size_tu:null,size_den:null,do_uu_tien:100,dang_ap_dung:true});renderSizes();};$("#btnAddRule").onclick=()=>{current.dieu_kien.push({ma_rule:"",ten_rule:"",do_uu_tien:100,muc_giam_pct:20,dang_ap_dung:true,bo_qua_tyle_neu_khong_lich_su_nhap:true});renderRules();};await loadAll();}
