import { supabase, startSessionKeeper } from './supabaseClient.js';
window.supabase=supabase; try{startSessionKeeper();}catch(e){console.warn(e)}
const $=s=>document.querySelector(s), nf=new Intl.NumberFormat('vi-VN');
const money=v=>nf.format(Math.round(Number(v||0))), pct=v=>`${(Number(v||0)*100).toFixed(1)}%`;
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(iso,n)=>{const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
let sb=supabase,hot=null,rows=[],total=0,page=1,currentMode='ALL',currentSnapshot=null,loading=false,periodKey='';
const cols=[
{data:'masp',title:'MÃ SP',width:145},{data:'tensp',title:'TÊN SP',width:165},{data:'main_group',title:'NHÓM CHÍNH',width:95},{data:'nhomhang',title:'NHÓM',width:70},{data:'nhacc',title:'NCC',width:90},
{data:'giale',title:'GIÁ LẺ',width:85,type:'numeric',numericFormat:{pattern:'0,0'}},{data:'gia_von_uoc_tinh',title:'GIÁ VỐN',width:85,type:'numeric',numericFormat:{pattern:'0,0'}},{data:'giam_gia_pct',title:'% GIẢM',width:60},
{data:'nhap_ky',title:'NHẬP KỲ',width:68},{data:'ban_ky',title:'BÁN KỲ',width:66},{data:'ban_cs1_ky',title:'BÁN CS1 KỲ',width:76},{data:'ban_cs2_ky',title:'BÁN CS2 KỲ',width:76},
{data:'tuoi_ma_ngay',title:'TUỔI MÃ',width:65},{data:'so_ngay_khong_ban',title:'NGÀY KB',width:68},{data:'ban_7d',title:'B7',width:48},{data:'ban_14d',title:'B14',width:50},{data:'ban_30d',title:'B30',width:50},{data:'ban_31_60d',title:'B30 TRƯỚC',width:74},{data:'ban_90d',title:'B90',width:50},{data:'ban_365d',title:'B365',width:55},
{data:'ton_cs1_thuc',title:'TỒN CS1',width:68},{data:'ton_cs2_thuc',title:'TỒN CS2',width:68},{data:'ton_tong_thuc',title:'TỒN TỔNG',width:72},{data:'ton_raw_sau_kiem',title:'TỒN RAW',width:70},
{data:'forecast_daily',title:'FORECAST/N',width:85},{data:'trend_30d_pct',title:'TREND %',width:68},{data:'sell_through_proxy_365',title:'ST365',width:62,renderer:(i,td,r,c,p,v)=>{td.textContent=pct(v);return td}},{data:'days_of_stock',title:'DAYS STOCK',width:78},
{data:'von_ton_uoc_tinh',title:'VỐN TỒN',width:100,type:'numeric',numericFormat:{pattern:'0,0'}},{data:'health_score',title:'ĐIỂM',width:52},{data:'phan_loai',title:'PHÂN LOẠI',width:100},{data:'action_code',title:'HÀNH ĐỘNG',width:115},{data:'action_reason',title:'LÝ DO',width:250}
];
function ensureHot(){if(hot)return;hot=new Handsontable($('#hot'),{data:rows,columns:cols,colHeaders:cols.map(x=>x.title),rowHeaders:true,readOnly:true,height:Math.max(480,innerHeight-410),stretchH:'none',manualColumnResize:true,columnSorting:true,filters:true,dropdownMenu:true,licenseKey:'non-commercial-and-evaluation',cells:(r)=>{const x=rows[r]||{},p={};if(x.data_error_flag)p.className='flag-error';else if(x.dead_flag)p.className='flag-dead';else if(x.overstock_flag)p.className='flag-over';else if(x.phan_loai==='MANH')p.className='flag-strong';return p;},afterOnCellDblClick:async(e,c)=>{if(c.row<0)return;const x=rows[c.row];try{if(window.StockQuick?.showFor)await window.StockQuick.showFor(document.body,x.masp);else if(window.stockQuickPopup)await window.stockQuickPopup(x.masp)}catch(err){console.warn(err)}}})}
function modeParams(){if(['MANH','TRUNG_BINH','YEU','MOI_THEO_DOI'].includes(currentMode))return{phan_loai:currentMode,flag:null};if(['DEAD','TAIL','OVERSTOCK','DATA_ERROR'].includes(currentMode))return{phan_loai:null,flag:currentMode};return{phan_loai:null,flag:null}}
let stockQuickLoadPromise=null;function ensureStockQuickLoaded(){if(window.StockQuick?.showFor||window.stockQuickPopup)return Promise.resolve(true);if(stockQuickLoadPromise)return stockQuickLoadPromise;stockQuickLoadPromise=new Promise(resolve=>{const sc=document.createElement('script');sc.src='/scripts/stockQuickPopup.js?v=20260908b';sc.onload=()=>resolve(true);sc.onerror=()=>resolve(false);document.head.appendChild(sc)});return stockQuickLoadPromise}
function filterParams(limit,offset,forceAll=false){const m=forceAll?{phan_loai:null,flag:null}:modeParams();return{p_snapshot_date:currentSnapshot,p_tu_ngay:$('#fromDate').value||null,p_den_ngay:$('#toDate').value||null,p_search:forceAll?null:($('#q').value.trim()||null),p_main_group:forceAll?null:($('#mainGroup').value||null),p_phan_loai:m.phan_loai,p_nhacc:forceAll?null:($('#nhacc').value.trim()||null),p_flag:m.flag,p_phatsinh:forceAll?'ALL':$('#activity').value,p_ton_status:forceAll?'ALL':$('#stockStatus').value,p_current_groups_only:forceAll?false:$('#currentGroupsOnly').checked,p_active_only:forceAll?false:$('#activeOnly').checked,p_limit:limit,p_offset:offset}}
async function ensurePeriod(force=false){const tu=$('#fromDate').value,den=$('#toDate').value;if(!tu||!den||tu>den)throw new Error('Khoảng ngày phân tích không hợp lệ');const key=`${tu}|${den}`;if(!force&&periodKey===key)return;$('#status').textContent=`Đang chuẩn bị kỳ ${tu} → ${den}...`;const{data,error}=await sb.rpc('prepare_suckhoe_hanghoa_period_v1_1',{p_tu_ngay:tu,p_den_ngay:den,p_force:force});if(error)throw error;if(!data?.ok)throw new Error(data?.message||'Không tính được kỳ phân tích');periodKey=key}
function renderSummary(s={}){const items=[['SKU lọc',s.sku],['Tồn SL',s.ton_sl],['Vốn tồn',money(s.von_ton)],['Nhập kỳ',s.nhap_ky],['Bán kỳ',s.ban_ky],['Mạnh',s.manh],['Trung bình',s.trung_binh],['Yếu',s.yeu],['Dead',s.dead],['Overstock',s.overstock],['Đuôi',s.tail],['Lỗi tồn',s.data_error],['Vốn yếu',money(s.von_yeu)],['Vốn dead',money(s.von_dead)],['GT tồn mác',money(s.gia_tri_ton_mac)]];$('#summary').innerHTML=items.map(([l,v])=>`<div class="kpi"><div class="v">${v??0}</div><div class="l">${l}</div></div>`).join('')}
async function loadPage(reset=false){if(loading)return;loading=true;try{if(reset)page=1;await ensurePeriod(false);const size=Number($('#pageSize').value||300);const{data,error}=await sb.rpc('rpc_suckhoe_hanghoa_bundle_v1_1',filterParams(size,(page-1)*size,false));if(error)throw error;const b=data||{};rows=b.rows||[];total=Number(b.total_rows||0);currentSnapshot=b.snapshot_date||currentSnapshot;renderSummary(b.summary||{});ensureHot();hot.updateSettings({data:rows});hot.render();const pages=Math.max(1,Math.ceil(total/size));$('#pageText').textContent=`Trang ${page}/${pages} · ${nf.format(total)} mã`;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;$('#status').textContent=`Kỳ phân tích ${b.tu_ngay} → ${b.den_ngay} · Tồn chốt ${b.snapshot_date}`;}catch(e){console.error(e);$('#status').innerHTML=`<span class="warn">Lỗi: ${e.message||e}</span>`}finally{loading=false}}
async function loadSnapshotHeader(){const{data,error}=await sb.rpc('rpc_suckhoe_hanghoa_summary_v1',{p_snapshot_date:currentSnapshot||null});if(error)throw error;currentSnapshot=data?.snapshot_date||currentSnapshot;if(currentSnapshot){$('#snapshotDate').value=currentSnapshot;if(!$('#toDate').value){$('#toDate').value=currentSnapshot;$('#fromDate').value=addDays(currentSnapshot,-29)}}}
async function refresh(){const dt=$('#snapshotDate').value||today();if(!confirm(`Nạp lại toàn bộ snapshot sức khỏe đến ${dt}?`))return;$('#btnRefresh').disabled=true;try{const{data,error}=await sb.rpc('refresh_suckhoe_hanghoa_v1',{p_den_ngay:dt});if(error)throw error;if(!data?.ok)throw new Error(data?.message||'Không refresh được');currentSnapshot=dt;$('#toDate').value=dt;if(!$('#fromDate').value)$('#fromDate').value=addDays(dt,-29);periodKey='';await ensurePeriod(true);await loadPage(true);alert(`Đã nạp ${nf.format(data.rows||0)} mã.`)}catch(e){alert('Lỗi: '+(e.message||e))}finally{$('#btnRefresh').disabled=false}}
function filterInfo(forceAll=false){return[{chi_tieu:'snapshot_date',gia_tri:currentSnapshot},{chi_tieu:'tu_ngay',gia_tri:$('#fromDate').value},{chi_tieu:'den_ngay',gia_tri:$('#toDate').value},{chi_tieu:'che_do',gia_tri:forceAll?'TOAN_BO':currentMode},{chi_tieu:'phat_sinh',gia_tri:forceAll?'ALL':$('#activity').value},{chi_tieu:'ton_status',gia_tri:forceAll?'ALL':$('#stockStatus').value},{chi_tieu:'main_group',gia_tri:forceAll?'':$('#mainGroup').value},{chi_tieu:'ncc',gia_tri:forceAll?'':$('#nhacc').value},{chi_tieu:'search',gia_tri:forceAll?'':$('#q').value},{chi_tieu:'current_groups_only',gia_tri:forceAll?false:$('#currentGroupsOnly').checked},{chi_tieu:'active_only',gia_tri:forceAll?false:$('#activeOnly').checked}]}
async function exportExcel(forceAll=false){if(!currentSnapshot){alert('Chưa có snapshot');return}await ensurePeriod(false);const btn=forceAll?$('#btnExport'):$('#btnExportFiltered'),old=btn.textContent;btn.disabled=true;btn.textContent='Đang xuất...';try{const batch=5000,all=[];let offset=0,totalRows=null,summary={};for(;;){$('#status').textContent=totalRows==null?`Đang lấy Excel: ${nf.format(all.length)} dòng...`:`Đang lấy Excel: ${nf.format(all.length)}/${nf.format(totalRows)} dòng...`;const{data,error}=await sb.rpc('rpc_suckhoe_hanghoa_bundle_v1_1',filterParams(batch,offset,forceAll));if(error)throw error;const b=data||{},part=b.rows||[];if(totalRows==null){totalRows=Number(b.total_rows||0);summary=b.summary||{}}all.push(...part);offset+=part.length;if(!part.length||offset>=totalRows)break}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(filterInfo(forceAll)),'00_FILTERS');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(all),'01_SKU_HEALTH');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.entries(summary).map(([k,v])=>({chi_tieu:k,gia_tri:v}))),'06_SUMMARY');const tag=forceAll?'TOANBO':'LOC';XLSX.writeFile(wb,`SucKhoeHangHoa_${tag}_${$('#fromDate').value}_${$('#toDate').value}.xlsx`,{compression:true});$('#status').textContent=`Đã xuất ${nf.format(all.length)} mã.`}catch(e){console.error(e);alert('Lỗi xuất Excel: '+(e.message||e))}finally{btn.disabled=false;btn.textContent=old}}
async function init(){ensureStockQuickLoaded().catch(()=>{});$('#snapshotDate').value=today();await loadSnapshotHeader();await loadPage(true);$('#btnRefresh').onclick=refresh;$('#btnExport').onclick=()=>exportExcel(true);$('#btnExportFiltered').onclick=()=>exportExcel(false);$('#btnSearch').onclick=()=>{periodKey='';loadPage(true)};$('#btnRecalcPeriod').onclick=async()=>{periodKey='';await ensurePeriod(true);await loadPage(true)};$('#pageSize').onchange=()=>loadPage(true);$('#prev').onclick=()=>{if(page>1){page--;loadPage(false)}};$('#next').onclick=()=>{page++;loadPage(false)};$('#tabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentMode=b.dataset.mode;loadPage(true)};['q','nhacc'].forEach(id=>$('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter')loadPage(true)}));$('#snapshotDate').onchange=async()=>{currentSnapshot=$('#snapshotDate').value||null;$('#toDate').value=currentSnapshot;$('#fromDate').value=addDays(currentSnapshot,-29);periodKey='';await loadPage(true)}}
init().catch(e=>{$('#status').textContent='Lỗi khởi tạo: '+(e.message||e)});
